services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual.
    build: .
    # Mapeia a porta 8000 do host para a porta 8000 do contêiner.
    container_name: container-imersao-devops
    ports:
      - "8000:8000"
    # Monta o diretório atual no contêiner para refletir as alterações de código em tempo real.
    # O banco de dados SQLite (escola.db) será criado e persistido no seu diretório local.
    volumes:
      - .:/app